[index_universe]
label = Index Universe
description = Orbital bubble chart of indexes sized by disk usage and event count
default_height = 500
allow_user_selection = true
disabled = 0
search_fragment = | rest /services/data/indexes | table title totalEventCount sizeGB
