[Calendar Heatmap - Live]
search = | makeresults count=365 \
| streamstats count as idx \
| eval _time = now() - ((idx - 1) * 86400) \
| eval count = case(random() % 5 == 0, 0, random() % 3 == 0, round(random() % 5), random() % 2 == 0, round(random() % 20), 1==1, round(random() % 60)) \
| bin _time span=1d \
| stats sum(count) as count by _time \
| sort _time \
| appendpipe [| stats count | where count=0 | eval _status="Awaiting activity data", _time=0, count=0]
dispatch.earliest_time = -1m
dispatch.latest_time = now
display.general.type = visualizations
display.visualizations.type = custom
display.visualizations.custom.type = calendar_heatmap.calendar_heatmap
display.visualizations.custom.calendar_heatmap.calendar_heatmap.lowColor = #ebedf0
display.visualizations.custom.calendar_heatmap.calendar_heatmap.highColor = #216e39
display.visualizations.custom.calendar_heatmap.calendar_heatmap.cellSize = 12
display.visualizations.custom.calendar_heatmap.calendar_heatmap.cellGap = 2
display.visualizations.custom.calendar_heatmap.calendar_heatmap.showMonthLabels = yes
