[package]
id = index_health

[id]
version = 0.1.0
name = index_health

[ui]
is_visible = 1
label = Index Health
show_in_nav = 0

[launcher]
author = rcastley
description = Monitor indexing activity, storage, and health status across Splunk indexes
version = 0.1.0

[install]
is_configured = 0
build = <@- buildNumber @>
check_for_updates = 0

[manifest]
category = Custom
