[F1 Track Info - Live]
search = index="data_drivers_f1_2025" sourcetype="SessionData" \
| stats latest(track_id) as track_id latest(track_length) as track_length latest(sector2_lap_distance_start) as sector2_lap_distance_start latest(sector3_lap_distance_start) as sector3_lap_distance_start \
| table track_id track_length sector2_lap_distance_start sector3_lap_distance_start
dispatch.earliest_time = rt-1m
dispatch.latest_time = rt
display.general.type = visualizations
display.visualizations.type = custom
display.visualizations.custom.type = f1_track_info.f1_track_info
display.visualizations.custom.f1_track_info.f1_track_info.trackWidth = 4
display.visualizations.custom.f1_track_info.f1_track_info.showTrackName = true
display.visualizations.custom.f1_track_info.f1_track_info.showSectorMarkers = true
display.visualizations.custom.f1_track_info.f1_track_info.textColor = #ffffff
