[Custom Single Value - Example]
search = | makeresults | eval value="Hello Splunk!"
dispatch.earliest_time = -1m
dispatch.latest_time = now
display.general.type = visualizations
display.visualizations.type = custom
display.visualizations.custom.type = custom_single_value.custom_single_value
display.visualizations.custom.custom_single_value.custom_single_value.field = value
display.visualizations.custom.custom_single_value.custom_single_value.color = #E20082
display.visualizations.custom.custom_single_value.custom_single_value.weight = bold
display.visualizations.custom.custom_single_value.custom_single_value.align = center
display.visualizations.custom.custom_single_value.custom_single_value.valign = middle
display.visualizations.custom.custom_single_value.custom_single_value.label =
display.visualizations.custom.custom_single_value.custom_single_value.labelColor = #888888
display.visualizations.custom.custom_single_value.custom_single_value.labelAlign = center
display.visualizations.custom.custom_single_value.custom_single_value.showGlow = false
