[id]
name = steampunk_gauge
version = 1.3.2

[install]
is_configured = true
build = 1

[package]
id = steampunk_gauge
check_for_updates = false

[ui]
is_visible = false
label = Steampunk Gauge

[launcher]
author = Community
description = Brass steampunk gauge with ivory dial face and classic needle.
version = 1.3.2
