[F1 ERS Energy - Live]
search = index="data_drivers_f1_2025" sourcetype="CarStatusData" \
| stats latest(ers_store_energy) as ers_store_energy latest(ers_deploy_mode) as ers_deploy_mode latest(ers_harvested_this_lap_mguk) as ers_harvested_this_lap_mguk latest(ers_harvested_this_lap_mguh) as ers_harvested_this_lap_mguh latest(ers_deployed_this_lap) as ers_deployed_this_lap by host \
| head 1
dispatch.earliest_time = rt-1m
dispatch.latest_time = rt
display.general.type = visualizations
display.visualizations.type = custom
display.visualizations.custom.type = f1_ers.f1_ers
display.visualizations.custom.f1_ers.f1_ers.accentColor = #ff8700
display.visualizations.custom.f1_ers.f1_ers.showLabels = true
display.visualizations.custom.f1_ers.f1_ers.showStats = true
display.visualizations.custom.f1_ers.f1_ers.layout = horizontal
display.visualizations.custom.f1_ers.f1_ers.showGlow = true
