[f1_ers]
label = F1 ERS Energy
description = Energy Recovery System battery bar with deploy mode, harvest and deploy stats
default_height = 200
allow_user_selection = true
disabled = 0
search_fragment = | stats latest(ers_store_energy) as ers_store_energy by driver
