[id]
name = bet_flow_map
version = 1.0.0

[install]
is_configured = true
build = 1

[package]
id = bet_flow_map

[ui]
is_visible = true
label = Geographic Bet Flow Map

[launcher]
author = rcastley
description = Geographic bet flow map showing animated particle flows from bet origin countries to match venue
version = 1.0.0
