[id]
name = data_pipeline
version = 1.0.0

[install]
is_configured = true
build = 1

[package]
id = data_pipeline

[ui]
is_visible = true
label = Data Pipeline

[launcher]
author = rcastley
description = Animated data pipeline showing ingestion volume flowing from sources into Splunk
version = 1.0.0
