[Data Pipeline - Live]
search = | tstats count where index=* by index | sort -count | head 10 | rename index as name, count as volume | appendpipe [| stats count | where count=0 | eval _status="Awaiting ingestion data", name="none", volume=0]
dispatch.earliest_time = -15m
dispatch.latest_time = now
display.general.type = visualizations
display.visualizations.type = custom
display.visualizations.custom.type = data_pipeline.data_pipeline
display.visualizations.custom.data_pipeline.data_pipeline.nameField = name
display.visualizations.custom.data_pipeline.data_pipeline.volumeField = volume
display.visualizations.custom.data_pipeline.data_pipeline.maxSources = 10
display.visualizations.custom.data_pipeline.data_pipeline.animSpeed = medium
display.visualizations.custom.data_pipeline.data_pipeline.showVolume = true
display.visualizations.custom.data_pipeline.data_pipeline.showChevron = true
display.visualizations.custom.data_pipeline.data_pipeline.showTotal = true
display.visualizations.custom.data_pipeline.data_pipeline.colorLow = #00B4D8
display.visualizations.custom.data_pipeline.data_pipeline.colorHigh = #65A637
display.visualizations.custom.data_pipeline.data_pipeline.volumeUnit = events
