[id]
name = search_activity
version = 1.0.0

[install]
is_configured = true
build = 1

[package]
id = search_activity

[ui]
is_visible = true
label = Search Activity

[launcher]
author = Splunk Viz
description = Horizontal glass tank showing search slot utilization by type
version = 1.0.0
