[Search Activity - Live]
search = | rest /services/server/status/resource-usage/splunk-processes | search search_props.sid=* | eval type=case(search_props.mode=="historical","scheduled", search_props.mode=="historical_fast","scheduled", search_props.provenance=="UI:Search","ad-hoc", 1=1,"other") | stats count by type | appendpipe [| stats count | where count=0 | eval _status="Awaiting search data", type="", count=0]
dispatch.earliest_time = -1m
dispatch.latest_time = now
display.general.type = visualizations
display.visualizations.type = custom
display.visualizations.custom.type = search_activity.search_activity
display.visualizations.custom.search_activity.search_activity.colorTheme = default
display.visualizations.custom.search_activity.search_activity.showGlow = true
display.visualizations.custom.search_activity.search_activity.animSpeed = medium
display.visualizations.custom.search_activity.search_activity.maxConcurrent = 50
display.visualizations.custom.search_activity.search_activity.warningThreshold = 60
display.visualizations.custom.search_activity.search_activity.criticalThreshold = 80
