[indexing_pipeline_flow]
label = Indexing Pipeline Flow
description = Animated Splunk indexing pipeline queues with fill levels and flow
default_height = 350
allow_user_selection = true
disabled = 0
search_fragment = index=_internal group=queue | stats latest(current_size) as avg_size by name
