[id]
name = scheduler_health
version = 1.0.0

[install]
is_configured = true
build = 1

[package]
id = scheduler_health

[ui]
is_visible = true
label = Scheduler Health

[launcher]
author = Splunk Viz
description = Three-tube vital signs for scheduler health
version = 1.0.0
