[id]
name = splunk_status_board
version = 1.0.0

[install]
is_configured = true
build = 1

[package]
id = splunk_status_board

[ui]
is_visible = true
label = Splunk Status Board

[launcher]
author = Splunk Viz
description = Glass-themed component health status board
version = 1.0.0
