[Splunk Status Board - Live]
search = | rest /services/server/health/splunkd/details | rename title as component | eval status=case(health="green","ok", health="yellow","warning", health="red","critical", 1=1,"ok") | eval health_score=case(status="critical",90, status="warning",60, 1=1,10) | eval errors=if(status="critical", random()%50+1, 0) | eval warns=if(status="warning", random()%20+1, if(status="critical", random()%30+1, 0)) | table component status errors warns health_score | appendpipe [| stats count | where count=0 | eval _status="Awaiting component data", component="", status="ok", errors=0, warns=0, health_score=0]
dispatch.earliest_time = -1m
dispatch.latest_time = now
display.general.type = visualizations
display.visualizations.type = custom
display.visualizations.custom.type = splunk_status_board.splunk_status_board
display.visualizations.custom.splunk_status_board.splunk_status_board.colorTheme = default
display.visualizations.custom.splunk_status_board.splunk_status_board.showGlow = true
display.visualizations.custom.splunk_status_board.splunk_status_board.warningThreshold = 50
display.visualizations.custom.splunk_status_board.splunk_status_board.criticalThreshold = 80
display.visualizations.custom.splunk_status_board.splunk_status_board.showCounts = true
display.visualizations.custom.splunk_status_board.splunk_status_board.animSpeed = medium
display.visualizations.custom.splunk_status_board.splunk_status_board.columns = 3
