[id]
name = line_trend_chart
version = 1.0.0

[install]
is_configured = true
build = 1

[package]
id = line_trend_chart
check_for_updates = false

[ui]
is_visible = true
label = Line Trend Chart

[launcher]
author = joehanse
description = Line/area trend chart with colored background sections, multiple series, smooth/straight lines, and hover crosshair
version = 1.0.0
