[Index Storage - Live]
search = | dbinspect index=* | eval temp=case(state=="hot","hot", state=="warm","warm", state=="cold","cold", 1=1,"other") | stats sum(sizeOnDiskMB) as sizeMB by index, temp | eval sizeGB=round(sizeMB/1024,2) | chart sum(sizeGB) as sizeGB by index, temp | rename index as title | eval hotGB=coalesce(hot,0), warmGB=coalesce(warm,0), coldGB=coalesce(cold,0) | eval sizeGB=hotGB+warmGB+coldGB | where sizeGB>0 | join type=outer title [| rest /services/data/indexes | eval maxGB=round(maxTotalDataSizeMB/1024,2) | table title maxGB] | table title sizeGB maxGB hotGB warmGB coldGB | sort -sizeGB | appendpipe [| stats count | where count=0 | eval _status="Awaiting index data", title="", sizeGB=0, maxGB=0, hotGB=0, warmGB=0, coldGB=0]
dispatch.earliest_time = -1m
dispatch.latest_time = now
display.general.type = visualizations
display.visualizations.type = custom
display.visualizations.custom.type = index_storage.index_storage
display.visualizations.custom.index_storage.index_storage.colorTheme = default
display.visualizations.custom.index_storage.index_storage.showGlow = true
display.visualizations.custom.index_storage.index_storage.animSpeed = medium
display.visualizations.custom.index_storage.index_storage.cellSize = auto
display.visualizations.custom.index_storage.index_storage.sortBy = size
